cloud:
  aws:
    credentials:
      access-key: AKIAQTFYZXNDTNJPWJP6
      secret-key: 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
    s3:
      bucket: bungaebowling-img-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false